import Head from 'next/head';
import MainLayout from '@/components/layouts/MainLayout';
import Banner from '@/components/views/home/banner';
import About from '@/components/views/home/about';
import Faq from '@/components/views/home/faq';
import Interfaces from '@/components/views/home/interfaces';

export default function Home() {
  return (
    <>
      <Head>
        <title>App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="home">
          <Banner />
          <About />
          <Faq />
          <Interfaces />
        </div>
      </MainLayout>
    </>
  );
}
